### PR TITLE
Small bugfixes and updates to modern Swift syntax

### PR DESCRIPTION
**Pull request by saagarjha**
* Name now shows instead of "Firstname Lastname"
* Fix bottom edge inset to account for the view
* Fix some assorted warnings

### CODE REVIEW

**Comment by avaidyam** [comment]
@saagarjha Thanks for your help, but I actually have a couple un-pushed commits that have made these fixes already, and I don't want to mess up the commit state! 👍 😄 

EDIT: Also, you're from MVHS? 😉

**Comment by avaidyam** [comment]
Also, heads up, before I can begin accepting big PRs for Parrot, I have yet to solidify the API, and many parts are still in motion right now.

**Comment by saagarjha** [comment]
Sure, I'll stick to filing bugs until then.

And yes, I am from MVHS :)

**Comment by avaidyam** [comment]
@saagarjha I'm an alumni. 😉 I will say that I don't recollect it fondly, however. But yes, thank you for using Parrot, and please do file issues for any improvements or bugs.

**Pull request closed without merging**
